apiVersion: batch/v1
kind: Job
metadata:
  name: tpcds-leader-ctas
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: loader
        image: python:3.11-slim
        command: ["bash","-lc"]
        args:
          - |
            pip -q install requests &&
            python -u /app/loader.py \
              --mode leader_ctas \
              --trino http://trino:8080 \
              --ctas-parallelism 2 \
              --trino-user bench \
              --sf 50 \
              --pg-catalog psql \
              --mongo-catalog mongodb \
              --target-schema tpcds \
              --drop
        volumeMounts:
          - name: app
            mountPath: /app
      volumes:
        - name: app
          configMap:
            name: trino-es-loader
            defaultMode: 0755
